"""added dropdown for repeat donation

Revision ID: 31794a2fcc90
Revises: 9d63d5be6ae6
Create Date: 2022-11-30 23:16:03.239888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31794a2fcc90'
down_revision = '9d63d5be6ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('repeat_option',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('repeat_option',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
