"""added medication to allergy

Revision ID: 360beae11354
Revises: 31794a2fcc90
Create Date: 2022-11-30 23:29:28.316656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360beae11354'
down_revision = '31794a2fcc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergy', schema=None) as batch_op:
        batch_op.drop_column('medication')

    # ### end Alembic commands ###
