"""all the FKs

Revision ID: 70ce0aef818f
Revises: 5cb9ab6c302d
Create Date: 2022-12-01 02:21:53.797438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70ce0aef818f'
down_revision = '5cb9ab6c302d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption', schema=None) as batch_op:
        batch_op.drop_index('animal_id')
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'])
        batch_op.create_foreign_key(None, 'application', ['app_id'], ['id'])
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    with op.batch_alter_table('allergy', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'])

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('employee_supervisor',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'contact', ['candidate_id'], ['id'])
        batch_op.create_foreign_key(None, 'employee', ['employee_supervisor'], ['id'])
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'])

    with op.batch_alter_table('backgroundcheck', schema=None) as batch_op:
        batch_op.drop_index('application_id')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])
        batch_op.create_foreign_key(None, 'application', ['application_id'], ['id'])

    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'])
        batch_op.create_foreign_key(None, 'employee', ['vet_id'], ['id'])

    with op.batch_alter_table('foster', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'])
        batch_op.create_foreign_key(None, 'application', ['app_id'], ['id'])
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'contact', ['id'], ['id'])

    with op.batch_alter_table('surgery', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'diagnosis', ['diagnosis_id'], ['id'])
        batch_op.create_foreign_key(None, 'employee', ['vet_id'], ['id'])

    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'diagnosis', ['diagnosis_id'], ['id'])

    with op.batch_alter_table('vaccination', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee', ['vet_id'], ['id'])
        batch_op.create_foreign_key(None, 'animal', ['animal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('surgery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('foster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('backgroundcheck', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('application_id', ['application_id'], unique=False)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('employee_supervisor',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('allergy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('adoption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('animal_id', ['animal_id'], unique=False)

    # ### end Alembic commands ###
