"""Initial migration

Revision ID: 8b31e3856934
Revises: 
Create Date: 2022-11-30 04:14:27.639602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b31e3856934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('ssn',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=False)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('ssn',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('credit_card',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('credit_card',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('ssn',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('ssn',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
