"""added date to payment

Revision ID: 9d63d5be6ae6
Revises: 1c1eaeb5f9ff
Create Date: 2022-11-30 22:49:03.831330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d63d5be6ae6'
down_revision = '1c1eaeb5f9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('employee_supervisor',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('application_status',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('repeat_option',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.alter_column('credit_card',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('name_on_card',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('billing_address',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('billing_address',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('name_on_card',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('credit_card',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('date')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('repeat_option',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('application_status',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('employee_supervisor',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
