"""changed ciminal to criminal

Revision ID: e288509e210a
Revises: 46a39d164467
Create Date: 2022-11-30 23:59:06.144999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e288509e210a'
down_revision = '46a39d164467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backgroundcheck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criminal_record', sa.String(length=150), nullable=False))
        batch_op.drop_column('ciminal_record')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backgroundcheck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciminal_record', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('criminal_record')

    # ### end Alembic commands ###
